CUDA_VISIBLE_DEVICES=1 python main_finetune.py \
    --accum_iter 1 \
    --batch_size 512 \
    --model vit_tiny_ours \
    --epochs 50 \
    --blr 1e-3 --layer_decay 0.75 \
    --finetune /nfs/bigdisk/varun/save/amt/p2/checkpoint-299.pth \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0 \
    --dist_url tcp://localhost:10006 \
    --data_path /data/add_disk0/varun/imagenet100/ \
    --output_dir /nfs/bigdisk/varun/save/amt/p2_ft/ \
    --log_dir /nfs/bigdisk/varun/save/amt/p2_ft/ \
    --nb_classes 100
